language: java
jdk: oraclejdk8
sudo: false
script: mvn package -f ch.sharpsoft.hexapod.embedded/pom.xml
deploy:
  provider: releases
  file: "/home/travis/build/helios57/hexapod/ch.sharpsoft.hexapod.embedded/target/ch.sharpsoft.hexapod.embedded-*.jar"
  skip_cleanup: true
  on:
    all_branches: true