// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package ch.sharpsoft.hexapod.transfer;

public final class Api {
  private Api() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface IMUOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ch.sharpsoft.hexapod.transfer.IMU)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 timestamp = 1;</code>
     */
    long getTimestamp();

    /**
     * <code>optional float ax = 2;</code>
     */
    float getAx();

    /**
     * <code>optional float ay = 3;</code>
     */
    float getAy();

    /**
     * <code>optional float az = 4;</code>
     */
    float getAz();

    /**
     * <code>optional float gx = 5;</code>
     */
    float getGx();

    /**
     * <code>optional float gy = 6;</code>
     */
    float getGy();

    /**
     * <code>optional float gz = 7;</code>
     */
    float getGz();

    /**
     * <code>optional float mx = 8;</code>
     */
    float getMx();

    /**
     * <code>optional float my = 9;</code>
     */
    float getMy();

    /**
     * <code>optional float mz = 10;</code>
     */
    float getMz();
  }
  /**
   * Protobuf type {@code ch.sharpsoft.hexapod.transfer.IMU}
   */
  public  static final class IMU extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ch.sharpsoft.hexapod.transfer.IMU)
      IMUOrBuilder {
    // Use IMU.newBuilder() to construct.
    private IMU(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private IMU() {
      timestamp_ = 0L;
      ax_ = 0F;
      ay_ = 0F;
      az_ = 0F;
      gx_ = 0F;
      gy_ = 0F;
      gz_ = 0F;
      mx_ = 0F;
      my_ = 0F;
      mz_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private IMU(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              timestamp_ = input.readInt64();
              break;
            }
            case 21: {

              ax_ = input.readFloat();
              break;
            }
            case 29: {

              ay_ = input.readFloat();
              break;
            }
            case 37: {

              az_ = input.readFloat();
              break;
            }
            case 45: {

              gx_ = input.readFloat();
              break;
            }
            case 53: {

              gy_ = input.readFloat();
              break;
            }
            case 61: {

              gz_ = input.readFloat();
              break;
            }
            case 69: {

              mx_ = input.readFloat();
              break;
            }
            case 77: {

              my_ = input.readFloat();
              break;
            }
            case 85: {

              mz_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.sharpsoft.hexapod.transfer.Api.internal_static_ch_sharpsoft_hexapod_transfer_IMU_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.sharpsoft.hexapod.transfer.Api.internal_static_ch_sharpsoft_hexapod_transfer_IMU_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.sharpsoft.hexapod.transfer.Api.IMU.class, ch.sharpsoft.hexapod.transfer.Api.IMU.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int AX_FIELD_NUMBER = 2;
    private float ax_;
    /**
     * <code>optional float ax = 2;</code>
     */
    public float getAx() {
      return ax_;
    }

    public static final int AY_FIELD_NUMBER = 3;
    private float ay_;
    /**
     * <code>optional float ay = 3;</code>
     */
    public float getAy() {
      return ay_;
    }

    public static final int AZ_FIELD_NUMBER = 4;
    private float az_;
    /**
     * <code>optional float az = 4;</code>
     */
    public float getAz() {
      return az_;
    }

    public static final int GX_FIELD_NUMBER = 5;
    private float gx_;
    /**
     * <code>optional float gx = 5;</code>
     */
    public float getGx() {
      return gx_;
    }

    public static final int GY_FIELD_NUMBER = 6;
    private float gy_;
    /**
     * <code>optional float gy = 6;</code>
     */
    public float getGy() {
      return gy_;
    }

    public static final int GZ_FIELD_NUMBER = 7;
    private float gz_;
    /**
     * <code>optional float gz = 7;</code>
     */
    public float getGz() {
      return gz_;
    }

    public static final int MX_FIELD_NUMBER = 8;
    private float mx_;
    /**
     * <code>optional float mx = 8;</code>
     */
    public float getMx() {
      return mx_;
    }

    public static final int MY_FIELD_NUMBER = 9;
    private float my_;
    /**
     * <code>optional float my = 9;</code>
     */
    public float getMy() {
      return my_;
    }

    public static final int MZ_FIELD_NUMBER = 10;
    private float mz_;
    /**
     * <code>optional float mz = 10;</code>
     */
    public float getMz() {
      return mz_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeInt64(1, timestamp_);
      }
      if (ax_ != 0F) {
        output.writeFloat(2, ax_);
      }
      if (ay_ != 0F) {
        output.writeFloat(3, ay_);
      }
      if (az_ != 0F) {
        output.writeFloat(4, az_);
      }
      if (gx_ != 0F) {
        output.writeFloat(5, gx_);
      }
      if (gy_ != 0F) {
        output.writeFloat(6, gy_);
      }
      if (gz_ != 0F) {
        output.writeFloat(7, gz_);
      }
      if (mx_ != 0F) {
        output.writeFloat(8, mx_);
      }
      if (my_ != 0F) {
        output.writeFloat(9, my_);
      }
      if (mz_ != 0F) {
        output.writeFloat(10, mz_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (ax_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, ax_);
      }
      if (ay_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, ay_);
      }
      if (az_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, az_);
      }
      if (gx_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, gx_);
      }
      if (gy_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, gy_);
      }
      if (gz_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, gz_);
      }
      if (mx_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, mx_);
      }
      if (my_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, my_);
      }
      if (mz_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(10, mz_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static ch.sharpsoft.hexapod.transfer.Api.IMU parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.sharpsoft.hexapod.transfer.Api.IMU parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.sharpsoft.hexapod.transfer.Api.IMU parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.sharpsoft.hexapod.transfer.Api.IMU parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.sharpsoft.hexapod.transfer.Api.IMU parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ch.sharpsoft.hexapod.transfer.Api.IMU parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.sharpsoft.hexapod.transfer.Api.IMU parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ch.sharpsoft.hexapod.transfer.Api.IMU parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ch.sharpsoft.hexapod.transfer.Api.IMU parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ch.sharpsoft.hexapod.transfer.Api.IMU parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.sharpsoft.hexapod.transfer.Api.IMU prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ch.sharpsoft.hexapod.transfer.IMU}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ch.sharpsoft.hexapod.transfer.IMU)
        ch.sharpsoft.hexapod.transfer.Api.IMUOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.sharpsoft.hexapod.transfer.Api.internal_static_ch_sharpsoft_hexapod_transfer_IMU_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.sharpsoft.hexapod.transfer.Api.internal_static_ch_sharpsoft_hexapod_transfer_IMU_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.sharpsoft.hexapod.transfer.Api.IMU.class, ch.sharpsoft.hexapod.transfer.Api.IMU.Builder.class);
      }

      // Construct using ch.sharpsoft.hexapod.transfer.Api.IMU.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;

        ax_ = 0F;

        ay_ = 0F;

        az_ = 0F;

        gx_ = 0F;

        gy_ = 0F;

        gz_ = 0F;

        mx_ = 0F;

        my_ = 0F;

        mz_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.sharpsoft.hexapod.transfer.Api.internal_static_ch_sharpsoft_hexapod_transfer_IMU_descriptor;
      }

      public ch.sharpsoft.hexapod.transfer.Api.IMU getDefaultInstanceForType() {
        return ch.sharpsoft.hexapod.transfer.Api.IMU.getDefaultInstance();
      }

      public ch.sharpsoft.hexapod.transfer.Api.IMU build() {
        ch.sharpsoft.hexapod.transfer.Api.IMU result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ch.sharpsoft.hexapod.transfer.Api.IMU buildPartial() {
        ch.sharpsoft.hexapod.transfer.Api.IMU result = new ch.sharpsoft.hexapod.transfer.Api.IMU(this);
        result.timestamp_ = timestamp_;
        result.ax_ = ax_;
        result.ay_ = ay_;
        result.az_ = az_;
        result.gx_ = gx_;
        result.gy_ = gy_;
        result.gz_ = gz_;
        result.mx_ = mx_;
        result.my_ = my_;
        result.mz_ = mz_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.sharpsoft.hexapod.transfer.Api.IMU) {
          return mergeFrom((ch.sharpsoft.hexapod.transfer.Api.IMU)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.sharpsoft.hexapod.transfer.Api.IMU other) {
        if (other == ch.sharpsoft.hexapod.transfer.Api.IMU.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getAx() != 0F) {
          setAx(other.getAx());
        }
        if (other.getAy() != 0F) {
          setAy(other.getAy());
        }
        if (other.getAz() != 0F) {
          setAz(other.getAz());
        }
        if (other.getGx() != 0F) {
          setGx(other.getGx());
        }
        if (other.getGy() != 0F) {
          setGy(other.getGy());
        }
        if (other.getGz() != 0F) {
          setGz(other.getGz());
        }
        if (other.getMx() != 0F) {
          setMx(other.getMx());
        }
        if (other.getMy() != 0F) {
          setMy(other.getMy());
        }
        if (other.getMz() != 0F) {
          setMz(other.getMz());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ch.sharpsoft.hexapod.transfer.Api.IMU parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ch.sharpsoft.hexapod.transfer.Api.IMU) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private float ax_ ;
      /**
       * <code>optional float ax = 2;</code>
       */
      public float getAx() {
        return ax_;
      }
      /**
       * <code>optional float ax = 2;</code>
       */
      public Builder setAx(float value) {
        
        ax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float ax = 2;</code>
       */
      public Builder clearAx() {
        
        ax_ = 0F;
        onChanged();
        return this;
      }

      private float ay_ ;
      /**
       * <code>optional float ay = 3;</code>
       */
      public float getAy() {
        return ay_;
      }
      /**
       * <code>optional float ay = 3;</code>
       */
      public Builder setAy(float value) {
        
        ay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float ay = 3;</code>
       */
      public Builder clearAy() {
        
        ay_ = 0F;
        onChanged();
        return this;
      }

      private float az_ ;
      /**
       * <code>optional float az = 4;</code>
       */
      public float getAz() {
        return az_;
      }
      /**
       * <code>optional float az = 4;</code>
       */
      public Builder setAz(float value) {
        
        az_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float az = 4;</code>
       */
      public Builder clearAz() {
        
        az_ = 0F;
        onChanged();
        return this;
      }

      private float gx_ ;
      /**
       * <code>optional float gx = 5;</code>
       */
      public float getGx() {
        return gx_;
      }
      /**
       * <code>optional float gx = 5;</code>
       */
      public Builder setGx(float value) {
        
        gx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float gx = 5;</code>
       */
      public Builder clearGx() {
        
        gx_ = 0F;
        onChanged();
        return this;
      }

      private float gy_ ;
      /**
       * <code>optional float gy = 6;</code>
       */
      public float getGy() {
        return gy_;
      }
      /**
       * <code>optional float gy = 6;</code>
       */
      public Builder setGy(float value) {
        
        gy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float gy = 6;</code>
       */
      public Builder clearGy() {
        
        gy_ = 0F;
        onChanged();
        return this;
      }

      private float gz_ ;
      /**
       * <code>optional float gz = 7;</code>
       */
      public float getGz() {
        return gz_;
      }
      /**
       * <code>optional float gz = 7;</code>
       */
      public Builder setGz(float value) {
        
        gz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float gz = 7;</code>
       */
      public Builder clearGz() {
        
        gz_ = 0F;
        onChanged();
        return this;
      }

      private float mx_ ;
      /**
       * <code>optional float mx = 8;</code>
       */
      public float getMx() {
        return mx_;
      }
      /**
       * <code>optional float mx = 8;</code>
       */
      public Builder setMx(float value) {
        
        mx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float mx = 8;</code>
       */
      public Builder clearMx() {
        
        mx_ = 0F;
        onChanged();
        return this;
      }

      private float my_ ;
      /**
       * <code>optional float my = 9;</code>
       */
      public float getMy() {
        return my_;
      }
      /**
       * <code>optional float my = 9;</code>
       */
      public Builder setMy(float value) {
        
        my_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float my = 9;</code>
       */
      public Builder clearMy() {
        
        my_ = 0F;
        onChanged();
        return this;
      }

      private float mz_ ;
      /**
       * <code>optional float mz = 10;</code>
       */
      public float getMz() {
        return mz_;
      }
      /**
       * <code>optional float mz = 10;</code>
       */
      public Builder setMz(float value) {
        
        mz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float mz = 10;</code>
       */
      public Builder clearMz() {
        
        mz_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ch.sharpsoft.hexapod.transfer.IMU)
    }

    // @@protoc_insertion_point(class_scope:ch.sharpsoft.hexapod.transfer.IMU)
    private static final ch.sharpsoft.hexapod.transfer.Api.IMU DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.sharpsoft.hexapod.transfer.Api.IMU();
    }

    public static ch.sharpsoft.hexapod.transfer.Api.IMU getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IMU>
        PARSER = new com.google.protobuf.AbstractParser<IMU>() {
      public IMU parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new IMU(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IMU> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IMU> getParserForType() {
      return PARSER;
    }

    public ch.sharpsoft.hexapod.transfer.Api.IMU getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ch_sharpsoft_hexapod_transfer_IMU_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ch_sharpsoft_hexapod_transfer_IMU_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tapi.proto\022\035ch.sharpsoft.hexapod.transf" +
      "er\"\204\001\n\003IMU\022\021\n\ttimestamp\030\001 \001(\003\022\n\n\002ax\030\002 \001(" +
      "\002\022\n\n\002ay\030\003 \001(\002\022\n\n\002az\030\004 \001(\002\022\n\n\002gx\030\005 \001(\002\022\n\n" +
      "\002gy\030\006 \001(\002\022\n\n\002gz\030\007 \001(\002\022\n\n\002mx\030\010 \001(\002\022\n\n\002my\030" +
      "\t \001(\002\022\n\n\002mz\030\n \001(\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ch_sharpsoft_hexapod_transfer_IMU_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ch_sharpsoft_hexapod_transfer_IMU_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ch_sharpsoft_hexapod_transfer_IMU_descriptor,
        new java.lang.String[] { "Timestamp", "Ax", "Ay", "Az", "Gx", "Gy", "Gz", "Mx", "My", "Mz", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
